version: 2.1

orbs:
  heroku: circleci/heroku@1.2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout      
      - run: npm install


workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git